---
version: '3'
# Example based onhttps://github.com/Stefen-Taime/docker-stack

services:
  postgres:
    container_name: ${CONTAINER_NAME}
    image: 'postgres:${PG_VER}'
    hostname: ${HOSTNAME}
    ports:
      - "5432:${PORT}"
    environment:
      TZ: ${TZ_SET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SRC_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    #    PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./scripts:/scripts
    networks:
      - docker-stack 

    
networks:
  docker-stack:      
